nav:
  - index.md
  - builders
  - node-operators
  - learn
  - Test Docs:
    - Overview: learn/test/index.md
    - Sample Page: learn/test/sample-page.md
  - ai-resources
  - About:
    - 'About Tanssi': 'https://www.tanssi.network/'
    - 'Tanssi TestNet': 'https://apps.tanssi.network/create'
