nav:
  - en/index.md
  - en/builders
  - en/node-operators
  - en/learn
  - en/ai-resources
  - About:
      - 'About Tanssi': 'https://www.tanssi.network/'
      - 'Tanssi TestNet': 'https://apps.tanssi.network/create'
